#!/bin/bash

usage()
{
	printf "$(gettext "Usage : 
 %s [options] [buildir]
 
Options :
 -n,--new
 -u,--update
 -p,--patch
 -c,--clean
 -b,--build
 -U,--user
 -a,--asroot
 -t,--template
 -f,--force
 -h,--help
 --nobuildeps
 ")" "${VPMSELF}"
}

done_msg()
{
	printf "\n"
}

fail_msg()
{
	printf "\n"
	die "$(gettext 'Failed to download %s')" ${1}
}

printme()
{
	local OPTS FUNCTION LOGER

	OPTS="$(getopt -o f:l: -l function:,loger -- "${@}")"
	eval set -- ${OPTS}
	while true
	do
		case ${1} in
			-f|--function) FUNCTION="${2}" ;;
			-l|--loger   ) LOGER="${2}"    ;;
			--           ) shift; break    ;;
		esac
		shift
	done
	[ -n "${LOGER}" ] && LOGER="${LOGER} => "
	
	FUNCTION="${FUNCTION:-log}"	
	case "${FUNCTION}" in
		msg|warn|error|die|debug|log|sys) true ;;
		* ) printf "$(gettext 'Invalid "%s" function')\n" "${FUNCTION}" ;;
	esac
	MESSAGE="${1}"
	shift 1

	case ${MESSAGE} in
		msg_run_func       )  ${FUNCTION} "${LOGER}$(gettext 'Running %s() function')" ${1//()};;
		msg_mis_args       )  ${FUNCTION} "${LOGER}$(gettext 'Missing arguments')" ;;
		msg_too_args       )  ${FUNCTION} "${LOGER}$(gettext 'Too many arguments')" ;;
		msg_fetching       )  ${FUNCTION} "${LOGER}$(gettext 'Downloading')" ;;
		msg_mis_file       )  ${FUNCTION} "${LOGER}$(gettext 'Missing %s file')" ${1} ;;
		msg_mis_dir        )  ${FUNCTION} "${LOGER}$(gettext 'Missing %s directory')" ${1} ;;
		msg_fail_load      )  ${FUNCTION} "${LOGER}$(gettext 'Failed to load "%s" file')" ${1} ;;
		msg_no_arch_compat )  ${FUNCTION} "${LOGER}$(gettext 'Incompatible %s arch for %s systems')" ${1} ${2} ;;
		msg_mis_stack      )  ${FUNCTION} "${LOGER}$(gettext 'No directory to back found')" ;;
		msg_fail_extract   )  ${FUNCTION} "${LOGER}$(gettext 'Failed to extract "%s" file')" ${1} ;;
		msg_file_damaged   )  ${FUNCTION} "${LOGER}$(gettext '%s file is damaged, stopping here')" ${1} ;;
		msg_aborting       )  ${FUNCTION} "${LOGER}$(gettext 'Aborting process ..')" ;;
		*                  )  ${FUNCTION} "${LOGER}${MESSAGE}" ${@} ;;
	esac
	
	return 0
}
